name: Publish

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Where to publish to
        options: 
        - pypi
        - test-pypi
      release:
        type: boolean
        description: Create a release
        default: false
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: publish-to-pypi
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Get version
        id: get-version
        run: |
          echo "version=$(poetry version --short)" >> $GITHUB_OUTPUT
      - name: Check version
        if: ${{ github.ref_type == 'tag' && (steps.get-version.outputs.version != github.ref_name) }}
        run: |
          exit 1
      - name: Publish to PyPI
        run: |
          poetry install
          poetry publish -r "${{ inputs.target  || 'pypi' }}" -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} --build
      - name: Create Release
        if: ${{ github.ref_type == 'tag' || inputs.release == true }}
        run: |
          gh release create ${{ steps.get-version.outputs.version }} \
          --title ${{ steps.get-version.outputs.version }} \
          --generate-notes \
          --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
